### PR TITLE
tutorial on reaction SMARTS

### PR DESCRIPTION
**Pull request by tentrillion**
This PR adds one new tutorial that shows a number of examples -- and a number of common pitfalls -- of using SMARTS reaction queries to create new molecules in rdkit.

### CODE REVIEW

**Comment by greglandrum** [comment]
Thanks for doing this. I will go through it and ensure that the automated testing works today/tomorrow and then do a PR with suggested changes against your repo.
I'm going to remove the hack around the linear molecules since that's something that will be fixed in the near future.

**Comment by tentrillion** [comment]
Everything looked mostly good to me.  My only hesitation was about PEP 8 compliance, but I think that's a lost cause for rdkit anyway, so I (think I) successfully merged your changes to my fork of the main repo.

**Comment by tentrillion** [comment]
Anything else that needs to happen before this PR gets merged?  Can I help with the Travis CI stuff in any way?

**Comment by greglandrum** [comment]
The tests need to pass, but I haven't had a chance to look at where the problems still are.
I'll try tomorrow.

**Comment by greglandrum** [comment]
Thanks for this!

**Pull request merged**
